apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaxstats
spec:
  rules:
    - host: jaxstats.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaxstats
                port:
                  number: 8000 