---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.corium.io
  resources:
  - coriummonitoralerts
  - coriummonitorcollectors
  - coriummonitorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.corium.io
  resources:
  - coriummonitoralerts/finalizers
  - coriummonitorcollectors/finalizers
  - coriummonitorconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - monitor.corium.io
  resources:
  - coriummonitoralerts/status
  - coriummonitorcollectors/status
  - coriummonitorconfigs/status
  verbs:
  - get
  - patch
  - update
