## Append samples of your project ##
resources:
- monitor_v1alpha1_coriummonitorconfig.yaml
- monitor_v1alpha1_coriummonitorcollector.yaml
- monitor_v1alpha1_coriummonitoralert.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
