apiVersion: stats.corium.io/v1alpha1
kind: JAXStatsConfig
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: jaxstatsconfig-sample
spec:
  # TODO(user): Add fields here
