apiVersion: stats.corium.io/v1alpha1
kind: JAXStatsConfig
metadata:
  name: jaxstats-sample
spec:
  enabled: true
  collectionInterval: 30
  metrics:
    - "restart_count"
    - "not_ready_count"
    - "pod_count"
  storageConfig:
    type: "configmap"
