apiVersion: stats.corium.io/v1alpha1
kind: JAXStatsAlert
metadata:
  name: jaxstats-alert-sample
spec:
  enabled: true
  collectorRef: "jaxstats-collector-sample"
  cooldownPeriod: "5m"
  rules:
    - name: "high-memory-usage"
      metric: "memory_usage"
      operator: ">"
      threshold: 85.0
      duration: "5m"
      severity: "warning"
    - name: "critical-gpu-usage"
      metric: "gpu_utilization"
      operator: ">"
      threshold: 95.0
      duration: "2m"
      severity: "critical"
  notifications:
    - type: "slack"
      endpoint: "https://hooks.slack.com/services/xxx/yyy/zzz"
      template: |
        Alert: {{ .AlertName }}
        Severity: {{ .Severity }}
        Metric: {{ .Metric }}
        Current Value: {{ .Value }}
        Threshold: {{ .Threshold }}
        Duration: {{ .Duration }}
