apiVersion: stats.corium.io/v1alpha1
kind: JAXStatsConfig
metadata:
  name: jaxstats-sample
spec:
  enabled: true
  collectionInterval: 60
  metrics:
    - "memory_usage"
    - "gpu_utilization"
    - "training_metrics"
  storageConfig:
    type: "prometheus"
    endpoint: "http://prometheus-server:9090"
    credentialsSecret: "prometheus-credentials"
