apiVersion: stats.corium.io/v1alpha1
kind: JAXStatsCollector
metadata:
  name: demo-collector
spec:
  targetNamespace: "default"
  configRef: "jaxstats-sample"
  metrics:
    - "restart_count"
    - "not_ready_count"
  resourceTypes:
    - "pods"
  selector:
    matchLabels:
      app: demo-workload
  collectionSchedule: "*/1 * * * *"
