name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: List files for debugging
      run: ls -lR

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.19.1'
        cache: 'npm'

    - name: Install Frontend Dependencies (if exists)
      run: |
        if [ -d "jaxstats/frontend" ]; then
          cd jaxstats/frontend
          npm install
        fi

    - name: Build Frontend (if exists)
      run: |
        if [ -d "jaxstats/frontend" ]; then
          cd jaxstats/frontend
          npm run build
        fi

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python Dependencies
      run: |
        pip install -r jaxstats/requirements.txt

    - name: Run Tests
      run: |
        cd jaxstats
        pytest 